#!/bin/sh
# About: Put the computer to sleep based on connman's network connection state
# Enter Sleep mode when state is idle or there are 5 consecutive icmp time outs

# Get the current state of connman's network connection
STATE="$(connmanctl state | awk -F= 'NR==1 {print $2}' | tr -d ' ')"

# Color definitions using escape codes
RED="$(tput setaf 1)"
GRN="$(tput setaf 2)"
BLU="$(tput setaf 4)"
YLW="$(tput setaf 3)"
# Reset
RST="$(tput sgr0)"

# date(1p) format
DATE="%a %d %b %Y"
TIME="${BLU}%I:%M:%S %p${RST}"

goto_sleep() {
	printf "$YLW==>$BLU %s$RST" 'Putting the computer to sleep in: '
	vsleep -r 5
	systemctl suspend
}

print_state() {
	date +"${1}${STATE}${RST} on $DATE at $TIME"
}
ping_check() {
	printf "$YLW==>$BLU %s$RST\n" 'Checking for ICMP replies'
	ping -c 5 google.com
}
case "$STATE" in
	online)
		# If 'online' do nothing
		print_state $GRN
		;;
	ready)
		# If 'ready' then check for ping replies
		# If there are 5 consecutive time outs then put the computer to sleep
		# Else do nothing
		print_state $YLW
		ping_check || goto_sleep
		;;
	idle)
		# If 'idle' then put the computer to sleep
		print_state $RED && goto_sleep
		;;
esac

exit $?
# vim: set ft=sh noet:
