#!/bin/sh
# xdotool key wrapper

alias xkey='xdotool key'

for KEY in "$@"; do
	case "$KEY" in
		[A-Za-z0-9])
			xkey $KEY
			;;
		'`') xkey grave ;;
		'~')
xkey asciitilde
;;
		'!') xkey exclam ;;
		'@') xkey at ;;
		'#') xkey numbersign ;;
		'$') xkey dollar ;;
		'%') xkey percent ;;
		'^') xkey asciicircum ;;
		'&') xkey ampersand ;;
		'*') xkey asterisk ;;
		'(') xkey parenleft ;;
		')') xkey parenright ;;
		'-') xkey minus ;;
		'_') xkey underscore ;;
		'+') xkey plus ;;
		'=') xkey equal ;;
		'[') xkey bracketleft ;;
		']') xkey bracketright ;;
		'{') xkey braceleft ;;
		'}') xkey braceright ;;
		';') xkey semicolon ;;
		':') xkey colon ;;
		"'") xkey apostrophe ;;
		'"') xkey quotedbl ;;
		',') xkey comma ;;
		'.') xkey period ;;
		'<') xkey less ;;
		'>') xkey greater ;;
		'/') xkey slash ;;
		'?') xkey question ;;
		'\\') xkey backslash ;;
		'|' | pipe) xkey bar ;;
		space) xkey $KEY ;;
		return) xkey Return ;;
		*)
			printf 'Error: %s\n' "$KEY: Unknown key" && exit 1
			;;
	esac
done

unalias xkey

exit $?
# vim: set ft=sh :et
