#!/bin/sh
# about: interactively choose and open a man page from a specific section
# menu opts 
OPTS="-i -b -l 4"

[ -n "$DISPLAY" ] && alias menu="xmenu $OPTS" || alias menu="slmenu $OPTS"

# If no section is specified then choose interactively from the list
[ -n "$1" ] && SEC="($1)" || \
	SEC="$(man -k . | cut -d ' ' -f 2 | sort | uniq | menu -p Section)"

tmux -q has-session && alias term="tmux new-window" || alias term="st -e"

man -k . | awk -v q="$SEC" '$2 == q { print }' | nl -s '' -n ln | menu -p $SEC \
	| awk '{ sub("\\(",""); sub("\\)",""); print $3 " " $2 }' | xargs term man
