#!/bin/sh
# simple random password generator
# number of characters in the password ( default: 30 )
BYTES=30
# number of passwords to generate ( default: 1 )
NUM=1
# special characters
SYM='!@#$%^&*()'
# characters to include in the password
CHARSET="A-Za-z0-9${SYM}"

usage() {
	echo "usage: ${0##*/} -n <no. of characters> -c <no. of passwords>"
	echo "(without any option a 30 characters password is generated)"
	echo
	echo "ex: generate 4 different passwords with 30 characters in each"
	echo "${0##*/} -c 4 -n 30"
}

while [ -n "$1" ]; do
	case $1 in
		-h) usage && exit 0 ;;
		-c) shift; BYTES=$1 ;;
		-n) shift; NUM=$1   ;;
		 *) usage && exit 1 ;;
	esac
	shift
done

tr -cd "$CHARSET" < /dev/urandom \
	| dd count=$NUM bs=$BYTES 2> /dev/null \
	| fold -w $BYTES
echo
