#!/bin/sh

alias player="amp"
alias menu="dmenu -i -l 10"
alias prettify1="xargs printf '\033[33m%s\033[0m\n'"
alias prettify2="toilet -t -f mono9 -F metal:border"

LIST=$HOME/etc/radio/list
STATION=${1:-"$(cut -d' ' -f1 $LIST | sort | menu -p "$(wc -l < $LIST) Found")"}

get_url() {
	awk -F ' ' -v f="$1" '$1 ~ f { print $2 }' $LIST
}

get_name() {
	awk -F ' ' -v f="$1" '$2 ~ f { print $1 }' $LIST
}

[ -z "$STATION" ] && { printf 'Error: %s\n' 'No url provided'; exit 1 ;} || {
	for u in $(get_url $STATION); do get_name $u | prettify2; player "$u"; done
}

exit $?
