#!/bin/sh
# Helper script to turn the touchpad on/off
#state=$(synclient -l | grep "TouchpadOff.*=.*0" | tr -d "A-Z a-z =")

_off()
{
	synclient TouchpadOff=1 && printf  'Touchpad \033[33;7m %s \n' "Off"
}

_on()
{
	synclient TouchpadOff=0 && printf  'Touchpad \033[32;7m %s \n' "On"
}

_toggle()
{
	local state=$(synclient -l | grep "TouchpadOff" | tr -cd "0-1")

	case $state in
		0) _off ;;
		1) _on  ;;
	esac
}

case $1 in
	on)
		_on ;;
	off) 
		_off ;;
	*)
		_toggle ;;
esac

exit 0
# vim: set ft=sh noet:
